---
- name: Ensure prometheus user exists
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    state: present
    shell: /bin/false

- name: Create Prometheus directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0755'
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_data_dir }}"

- name: Download Prometheus
  ansible.builtin.get_url:
    url: "{{ prometheus_download_url }}"
    dest: "/tmp/prometheus.tar.gz"
    mode: '0644'

- name: Extract Prometheus archive
  ansible.builtin.unarchive:
    src: "/tmp/prometheus.tar.gz"
    dest: "/opt"
    remote_src: yes

- name: Copy Prometheus binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: "/usr/local/bin/"
    mode: '0755'
    remote_src: yes

- name: Copy Prometheus config to /etc/prometheus/prometheus.yml
  ansible.builtin.template:
    src: "prometheus.yml.j2"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: '0644'
  notify: Reload Prometheus

- name: Copy Prometheus service file
  ansible.builtin.template:
    src: "prometheus.service.j2"
    dest: "/etc/systemd/system/prometheus.service"
    mode: '0644'
  notify: Reload systemd

- name: Start and enable Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    enabled: yes
    state: started
