---
- name: "Add FluentBit repository GPG key"
  ansible.builtin.apt_key:
    url: "https://packages.fluentbit.io/fluentbit.key"
    state: "present"

- name: "Add FluentBit official repository"
  ansible.builtin.apt_repository:
    repo: "{{ fluentbit_apt_repo }}"
    state: "present"

- name: "Install FluentBit"
  ansible.builtin.apt:
    name: "td-agent-bit"
    state: "present"
    update_cache: "yes"

- name: "Copy FluentBit configuration"
  ansible.builtin.template:
    src: "fluent-bit.conf.j2"
    dest: "{{ fluentbit_conf_dir }}/td-agent-bit.conf"

- name: "Enable and start FluentBit service"
  ansible.builtin.systemd:
    name: "td-agent-bit"
    enabled: "yes"
    state: "started"